### ISSUE TITLE
Introduce VIRTIO_F_IO_BARRIER for hardware virtio devices

### ISSUE THREAD

**Issue by btw616** [oasis-tcs/virtio-spec#10]
Introduce `VIRTIO_F_IO_BARRIER` for hardware based virtio devices.
More details could be found from the proposal:

https://lists.oasis-open.org/archives/virtio-dev/201805/msg00046.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3211
