### ISSUE TITLE
document constant format

### ISSUE THREAD

**Issue by mstsirkin** [oasis-tcs/virtio-spec#101]
The spec inconsistently uses either the C #define or the C enum syntax to refer to numeric values in code listings. The C << operation is also sometimes used to refer to specific bits.
We should be explicit and consistent in all this.

Proposal: https://lists.oasis-open.org/archives/virtio-comment/202103/msg00034.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3598

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3604
