### ISSUE TITLE
content: reserve device ID 38 for parameter server device

### ISSUE THREAD

**Issue by chenhao94** [oasis-tcs/virtio-spec#102]
Please reserve device ID 38 for the Parameter Server device as requested in https://lists.oasis-open.org/archives/virtio-dev/202103/msg00061.html

**Comment by chenhao94** [comment]
Use 38 instead, requested in https://lists.oasis-open.org/archives/virtio-dev/202103/msg00061.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3605
