### ISSUE TITLE
virtio-net: define USO feature

### ISSUE THREAD

**Issue by ybendito** [oasis-tcs/virtio-spec#104]
There is a USO (UDP Segmentation offload) feature that is going to be a requirement of Windows for server-grade network adapters. It is different from existing UFO:
- UFO fragments the UDP packet and only first fragment carries the UDP header (SKB_GSO_UDP in the Linux network stack)
- USO segments the UDP packet, each segment has a UDP header and IP identification field is incremented for each segment. It is designated as SKB_GSO_UDP_L4 in the Linux network stack but not supported by virtio-net
The host USO feature is to be defined for virtio-net.

**Comment by ybendito** [comment]
https://lists.oasis-open.org/archives/virtio-comment/202104/msg00005.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3618
