### ISSUE TITLE
snd: extend virtio sound device with audio controls

### ISSUE THREAD

**Issue by golubevmikhail** [oasis-tcs/virtio-spec#107]
Audio control elements should be used to set the volume level, mute/unmute the audio signal, switch different modes/states of the virtual sound device, etc. Support of audio controls should be guarded by a reserved feature bit.

Proposed patch: https://lists.oasis-open.org/archives/virtio-comment/202104/msg00013.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3709
