### ISSUE TITLE
Introduce SR-IOV support

### ISSUE THREAD

**Issue by btw616** [oasis-tcs/virtio-spec#11]
Allocate `VIRTIO_F_SR_IOV` for virtio devices which support SR-IOV.
More details could be found from the proposal:
 
https://lists.oasis-open.org/archives/virtio-dev/201805/msg00154.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3218
