### ISSUE TITLE
Add virtio-gpio base specification

### ISSUE THREAD

**Issue by vireshk** [oasis-tcs/virtio-spec#110]
https://lists.oasis-open.org/archives/virtio-dev/202108/msg00058.html

**Comment by vireshk** [comment]
@cohuck @mstsirkin

Will it be possible to merge the base gpio specifications first [1], which are already reviewed by Linus and Arnd ?

IRQ stuff still needs some work it seems, will keep on working on it. This will also enable us to merge the base driver for Linux as well. Thanks.

[1] https://lists.oasis-open.org/archives/virtio-dev/202107/msg00233.html

**Comment by cohuck** [comment]
> Will it be possible to merge the base gpio specifications first [1], which are already reviewed by Linus and Arnd ?

If you think that part is in good shape already, we certainly don't have to wait for the rest.

> IRQ stuff still needs some work it seems, will keep on working on it. This will also enable us to merge the base driver for Linux as well. Thanks.
> 
> [1] https://lists.oasis-open.org/archives/virtio-dev/202107/msg00233.html

Can you please update this request (description, not comment) to point to the patch you want to include? If you prefer, you can also post the agreed part separately and link to that, but I don't think that's needed.

For the IRQ part, just open a new PR.

**Comment by vireshk** [comment]
> If you think that part is in good shape already, we certainly don't have to wait for the rest.

Yes, this part looks fairly solid and stable.

> Can you please update this request (description, not comment) to point to the patch you want to include? If you prefer, you can also post the agreed part separately and link to that, but I don't think that's needed.
>

I have tried to do that, though I am not sure if I did it correctly. I updated the subject itself, couldn't find a separate description field.

> For the IRQ part, just open a new PR.

Perfect.

Thanks

**Comment by cohuck** [comment]
> > Can you please update this request (description, not comment) to point to the patch you want to include? If you prefer, you can also post the agreed part separately and link to that, but I don't think that's needed.
> 
> I have tried to do that, though I am not sure if I did it correctly. I updated the subject itself, couldn't find a separate description field.

The title should remain at "Add virtio-gpio specification" (or maybe "Add virtio-gpio base specification".)

For the description, you should just be able to edit it and simply add a link to the patch (and remove the existing pointers to the complete series)? The reason why we need that is that we generate the ballot text from that description, so it needs to be clear for the voters what they are voting on.

**Comment by vireshk** [comment]
> For the description, you should just be able to edit it and simply add a link to the patch (and remove the existing pointers to the complete series)?

I think I got confused because it is called as a "comment" in github (it says vireshk commented on jun 3).

Done now, hopefully correctly this time.

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3637
