### ISSUE TITLE
 virtio-rpmb: clarrify the description for multi-block reads

### ISSUE THREAD

**Issue by stsquad** [oasis-tcs/virtio-spec#113]
As discussed on the mailing list:

  https://lists.oasis-open.org/archives/virtio-comment/202107/msg00119.html

As a PR:

  https://github.com/stsquad/virtio-spec/tree/pr/rpmb-clarification

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3635
