### ISSUE TITLE
virtio-gpu context types

### ISSUE THREAD

**Issue by gurchetansingh** [oasis-tcs/virtio-spec#117]
These patches:
(1) adds existing features already used by driver/devices in spec
(2) adds the new CONTEXT_INIT feature

The latest patches are available at:
https://lists.oasis-open.org/archives/virtio-comment/202109/msg00014.html
https://lists.oasis-open.org/archives/virtio-comment/202109/msg00015.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3645
