### ISSUE TITLE
virtio-iommu: Rework the bypass feature

### ISSUE THREAD

**Issue by jpbrucker** [oasis-tcs/virtio-spec#119]
Add VIRTIO_IOMMU_F_BYPASS_CONFIG which supersedes VIRTIO_IOMMU_F_BYPASS, allowing a device implementation to boot in bypass mode and multiple drivers (firmware, guest OS) to flip the bypass state via config space. It also introduces bypass domains, which allows a driver to enable bypass at a finer granularity.

Version 1 of the specification change: https://www.mail-archive.com/virtio-dev@lists.oasis-open.org/msg07817.html
Version 2: https://www.mail-archive.com/virtio-dev@lists.oasis-open.org/msg07898.html
Version 3: https://www.mail-archive.com/virtio-dev@lists.oasis-open.org/msg07969.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3664
