### ISSUE TITLE
virtio-net: define USO host->guest features

### ISSUE THREAD

**Issue by ybendito** [oasis-tcs/virtio-spec#120]
In addition to already defined USO (guest to host) feature, need to define respective host to guest feature that allows the guest to receive large UDP packets.
In case of guest-to-guest traffic this let us avoid segmentation of the packet that was sent with USO.
The feature is similar to VIRTIO_NET_F_GUEST_TSO4/6 but targets UDP packets.

https://lists.oasis-open.org/archives/virtio-comment/202110/msg00010.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3708
