### ISSUE TITLE
Support describing virtio-pmem as a shared memory region

### ISSUE THREAD

**Issue by taylorstark** [oasis-tcs/virtio-spec#121]
Update the virtio-pmem spec to add support for describing the pmem region as a shared memory window. This is required to support virtio-pmem in Hyper-V, since Hyper-V only allows PCI devices to operate on memory ranges defined via BARs. When using the virtio PCI transport, shared memory regions are described via PCI BARs.

https://lists.oasis-open.org/archives/virtio-comment/202111/msg00008.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3669
