### ISSUE TITLE
Allow the driver to reset a queue individually

### ISSUE THREAD

**Issue by fengidri** [oasis-tcs/virtio-spec#124]
Update the virtio spec by adding optional new feature that extends the basic facility to allow the driver to reset a virtqueue. This main motivation is to support the reset function of the queue of the network device.

Proposed patch set: https://lists.oasis-open.org/archives/virtio-dev/202111/msg00011.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3676
