### ISSUE TITLE
[Question] - status about virtio-video

### ISSUE THREAD

**Issue by zhouziyang** [oasis-tcs/virtio-spec#126]
I'm author of [remote-android](https://github.com/remote-android) projects (it's about Virtualized Android). The virtual Android may be renderred by Intel / AMD / ... or virtio GPU, and I'm interested about the encoder / decorder parts of the virtio-video.
Can someone share about the progress of the virtio-video? (kernel, qemu, virtio-device etc.)
Thanks~~

**Comment by cohuck** [comment]
Hi,
the video device has not yet been added to the spec (but an ID has been reserved).

The latest status I'm aware of is https://lists.oasis-open.org/archives/virtio-dev/202111/msg00031.html -- if you are interested in the device for your project, it might be a good idea to talk to the authors.

Do you have any further concerns? If not, I'll close this issue, as we only use issues as a vehicle for including spec updates. Further discussion should happen on the mailing lists.

**Comment by zhouziyang** [comment]
I will check the mail list, thanks~~
