### ISSUE TITLE
Reserved Feature bits numbering is not aligned

### ISSUE THREAD

**Issue by maxgurtovoy** [oasis-tcs/virtio-spec#128]
Feature bits 38, 39, 40 are taken by VIRTIO_F_NOTIFICATION_DATA, VIRTIO_F_NOTIF_CONFIG_DATA and VIRTIO_F_RING_RESET but this is not aligned with "Feature Bits" section.
https://lists.oasis-open.org/archives/virtio-comment/202201/msg00007.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3677
