### ISSUE TITLE
Device specific Feature bits numbering is not aligned

### ISSUE THREAD

**Issue by maxgurtovoy** [oasis-tcs/virtio-spec#131]
Feature bits 56 to 63 are taken by the virtio-net device and not reflected in the generic feature bits accounting.

Proposed patch: https://lists.oasis-open.org/archives/virtio-comment/202201/msg00063.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3682
