### ISSUE TITLE
virtio-vsock: add seqpacket support

### ISSUE THREAD

**Issue by stefano-garzarella** [oasis-tcs/virtio-spec#132]
`seqpacket` sockets provide in-order, guaranteed, connection-oriented delivery with message and record boundaries.

To support `seqpacket` in virtio-vsock devices, we add:
- a new socket type (`VIRTIO_VSOCK_TYPE_SEQPACKET`)
- a new feature (`VIRTIO_VSOCK_F_SEQPACKET`)
- two flags to support message and record boundaries (`VIRTIO_VSOCK_SEQ_EOM`. `VIRTIO_VSOCK_SEQ_EOR`).

Latest series:
https://lists.oasis-open.org/archives/virtio-comment/202201/msg00050.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3680
