### ISSUE TITLE
Enhance device requirements for feature bits

### ISSUE THREAD

**Issue by btw616** [oasis-tcs/virtio-spec#14]
Some guests might not resume properly from suspend a feature changes under their feet.
This applies to Linux guests and the SRIOV feature, offloads for the networking
device and highly likely to more devices and features.

Forbid devices from changing features even across a reset but keep
the door open for white-listing specific feature bits where we will know
what we are doing (e.g. the specific feature bit is re-sampled each time,
failure to resume is the intended behaviour etc).

https://lists.oasis-open.org/archives/virtio-dev/201806/msg00098.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3220
