### ISSUE TITLE
virtio-net: interrupt coalescing feature

### ISSUE THREAD

**Issue by Alvaro-Karsz** [oasis-tcs/virtio-spec#141]
This patch adds a new interrupt coalescing feature for a VirtIO net device: VIRTIO_NET_F_NOTF_COAL(53).

A device that negotiates this feature can receive VIRTIO_NET_CTRL_NOTF_COAL commands through the control virtqueue.

- VIRTIO_NET_CTRL_NOTF_COAL_TX_SET: set tx_usecs and tx_max_packets parameters.
- VIRTIO_NET_CTRL_NOTF_COAL_RX_SET: set rx_usecs and rx_max_packets parameters.

spec patch:
https://lists.oasis-open.org/archives/virtio-comment/202206/msg00100.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3715
