### ISSUE TITLE
virtio-vsock: add VIRTIO_VSOCK_F_NO_IMPLIED_STREAM feature bit

### ISSUE THREAD

**Issue by stefano-garzarella** [oasis-tcs/virtio-spec#142]
Initially virtio-vsock only supported the stream type, which is why
there was no feature. Later we added the seqpacket type and in the future
we may have other types (e.g. datagram).

seqpacket is an extension of stream, so it might be implied that if
seqpacket is supported, stream is too, but this might not be true for
other types.

As we discussed [here](http://markmail.org/message/2s3qd74drgjxkvte) should be better to add a new
VIRTIO_VSOCK_F_NO_IMPLIED_STREAM feature bit to avoid this implication.

Let's also add normative sections to better define the behavior when
VIRTIO_VSOCK_F_NO_IMPLIED_STREAM is negotiated or not.

Latest patch sent:
https://lists.oasis-open.org/archives/virtio-comment/202207/msg00034.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3722
