### ISSUE TITLE
Reserve device ID 43 for Camera Device

### ISSUE THREAD

**Issue by Hrishivarya** [oasis-tcs/virtio-spec#148]
Please reserve device ID 43 for the Camera device as requested in https://lists.oasis-open.org/archives/virtio-dev/202210/msg00021.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3733

**Comment by veena14** [comment]
Inquiry on virtio-camera support in the spec.
Is there any ongoing effort to support virtio-camera ?
