### ISSUE TITLE
Use a consistent wording for device status

### ISSUE THREAD

**Issue by btw616** [oasis-tcs/virtio-spec#15]
There is a part called "device status field" in a Virtio device. Currently, both of \field{status} and \field{device status} are used to refer to it, which is a bit confusing. This proposal is to change the spec to use \field{device status} consistently. More details could be found from the below link:

https://lists.oasis-open.org/archives/virtio-dev/201806/msg00131.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3243
