### ISSUE TITLE
reserve device ID 44 for ISM device

### ISSUE THREAD

**Issue by fengidri** [oasis-tcs/virtio-spec#150]
The virtio-ism device provides the ability to share memory between
different guests on a host. A guest's memory got from ism device can be
shared with multiple peers at the same time. This shared relationship
can be dynamically created and released.

The shared memory obtained from the device is divided into multiple ism
regions for share. ISM device provides a mechanism to notify other ism
region referrers of content update events.

https://lists.oasis-open.org/archives/virtio-dev/202211/msg00198.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3743
