### ISSUE TITLE
Split individual virtio device spec to its own file

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#153]
Problem statement:
Relatively several of the recent device specification are maintained in their own specification file.
Such separate files enables better maintenance of the specification overall.

However, several of the initial virtio device specifications are located in single file. Current specification is maintained as mixed mode.

Solution:
Hence follow the modular approach practice of individual files for all devices.

Patches: https://lists.oasis-open.org/archives/virtio-dev/202301/msg00210.html

**Comment by paravmellanox** [comment]
@mstsirkin ,

Can we please start the vote on it if it is needed?

As you know, 
Patches do not change any part of the specification outcome
except fixing the spelling errors.
It only changes how the specification is maintained.

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3746

**Comment by paravmellanox** [comment]
@mstsirkin ,
link to the v3 is updated now in the description.

**Comment by paravmellanox** [comment]
@mstsirkin 
link to v4 is updated now in the description.

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3748
