### ISSUE TITLE
virtio-network: Avoid confusion between a card and a device

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#154]
Problem statement:
Ethernet card is a relatively vague term in context of virtio network
device specification. A Ethernet card in the industry has one to
multiple ports, one to multiple PCI functions.

Historically virtio network device is documented as a Ethernet card.
However it is usually just a single virtual Ethernet device.

Solution:
Hence, avoid this confusing term 'card' and align the specification
to adhere to widely used specification term as 'device' used for all
virtio device types.

Solution patch: https://lists.oasis-open.org/archives/virtio-dev/202301/msg00280.html

**Comment by paravmellanox** [comment]
@mstsirkin 

This is reviewed and ready for Ballot vote.

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3749

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3752
