### ISSUE TITLE
virtio-net: Fix introductory description

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#156]
Problem statement:

Control VQ of virtio net device is used for three very different things.
This includes
(a) steering controls,
(b) offload controls
(c) notification coalescing controls

However old description was not updated, which indicates only (a) as the role of CVQ.

Additionally, virtio net device introduction around CVQ and otherwise is very simple.  Describe the packet send/receive bit better along with the SQ/RQ enqueue/dequeue operation.

Proposal:
Update the documentation to reflect the generic nature of cvq for dynamic changes, rather than individual items.
Patch link: https://lists.oasis-open.org/archives/virtio-dev/202302/msg00308.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3758

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3761
