### ISSUE TITLE
Split transport specific files

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#157]
Problem statement:
Currently several tens of pages worth of transport specific content is situated in single file.
Many parts of the specification are already maintained in separate files.
Such separate files enables better maintenance of the specification overall.

Solution:
Follow the approach similar to rest of the spec, and keep transport specific spec in their individual files.

Link to patches: https://lists.oasis-open.org/archives/virtio-dev/202302/msg00578.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3763
