### ISSUE TITLE
virtio-net: Mention that VIRTIO_NET_F_HASH_REPORT requires  VIRTIO_NET_F_CTRL_VQ.

### ISSUE THREAD

**Issue by Alvaro-Karsz** [oasis-tcs/virtio-spec#158]
If the VIRTIO_NET_F_HASH_REPORT feature is negotiated, the driver may
send VIRTIO_NET_CTRL_MQ_HASH_CONFIG commands, thus, the control VQ
is needed.

Since this was missed in 1.2, we can now add it as a "SHOULD".

https://lists.oasis-open.org/archives/virtio-comment/202302/msg00031.html

**Comment by mstsirkin** [comment]
unfortunately in 1.2 we already did not make this a dependency.
so we can make it a SHOULD since it makes sense, but not a MUST
without a feature bit.

**Comment by Alvaro-Karsz** [comment]
Ok, I'll fix the github issue and the patch.

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3755
