### ISSUE TITLE
virtio-net: Fix and update VIRTIO_NET_F_NOTF_COAL feature

### ISSUE THREAD

**Issue by Alvaro-Karsz** [oasis-tcs/virtio-spec#159]
Make several improvements to the notification coalescing feature, including:

- Consolidating virtio_net_ctrl_coal_tx and virtio_net_ctrl_coal_rx
  into a single struct, virtio_net_ctrl_coal, as they are identical.
- Emphasizing that the coalescing commands are best-effort.
- Defining the behavior of coalescing with regards to delivering
  notifications when a change occur.
- Stating that the commands should apply to all the receive/transmit
  virtqueues.
- Stating that every receive/transmit virtqueue should count it's own
  packets.
- A new intro explaining the entire coalescing operation.

https://lists.oasis-open.org/archives/virtio-comment/202302/msg00431.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3760
