### ISSUE TITLE
rework notifications terminology

### ISSUE THREAD

**Issue by halil-pasic** [oasis-tcs/virtio-spec#16]
The terminology around notifications is currently somewhat fragmented. Unify notifications terminology using available and used buffer notification consistently for the virtqueue notifications. Consistent use of the term configuration change notification is of concern.

Proposal:
https://lists.oasis-open.org/archives/virtio/201806/msg00032.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3228
