### ISSUE TITLE
virtio-net: improve configuration layout description

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#161]
Problem statement:

1. Currently virtio net configuration structure is defined in middle of the fields. Fields are explained before introducing the configuration structure itself.
2. Multiple fields and config structure both are described read only (duplication)
3. it is not part of the normative statement.

Solution:
Improve above description.

Patch link: https://lists.oasis-open.org/archives/virtio-dev/202302/msg00556.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3764

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3765
