### ISSUE TITLE
virtio-net: define the VIRTIO_NET_F_CTRL_RX_EXTRA feature bit

### ISSUE THREAD

**Issue by Alvaro-Karsz** [oasis-tcs/virtio-spec#162]
The VIRTIO_NET_F_CTRL_RX_EXTRA feature bit is mentioned in the spec
since version 1.0, but it's not properly defined.

This patch defines the feature bit and defines the dependency on VIRTIO_NET_F_CTRL_VQ.

Since this dependency is missing in previous versions, we add it now as
a "SHOULD".

https://lists.oasis-open.org/archives/virtio-comment/202302/msg00508.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3762
