### ISSUE TITLE
Bring consistency to identify a virtuque by number

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#163]
Problem statement:

1. Currently, a virtqueue is identified between the driver and device
interchangeably using either number of index terminology.

2. Between PCI and MMIO transport the queue size (depth) is
defined as queue_size and QueueNum respectively.

To avoid confusion and to have consistency, unify them to use as Number.

Solution:
Use virtqueue index description and rename MMIO register as QueueSize.

Patch to vote: https://lists.oasis-open.org/archives/virtio-comment/202305/msg00101.html
Patch for maintainer to merge for automation: https://lore.kernel.org/virtio-comment/20230505014614.571520-1-parav@nvidia.com/

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3777
