### ISSUE TITLE
Support transitional device for PCIe VF

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#167]
Currently transitional device for PCIe is half baked.
Such as PCIe VF cannot be a transitional device.

A transitional device support for the PCIe VF is needed to expose the legacy interface.

Detailed requirements, use case, and the proposed solution is in the cover letter at [1].

patch link: [1] https://lists.oasis-open.org/archives/virtio-comment/202307/msg00155.html

patch for automation: https://lore.kernel.org/virtio-comment/20230711150135.222793-1-parav@nvidia.com/T/#u

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3787
