### ISSUE TITLE
Correct virtual queue to virtqueue for MMIO transport

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#168]
Problem: MMIO device refers to the virtqueue as "virtual queue".

virtio specification all over refers to this as virtqueue object.

Solution: Correct it to refer to it as virtqueue.

Patch for vote: https://lists.oasis-open.org/archives/virtio-comment/202305/msg00185.html
Patch for maintainer automation: https://lore.kernel.org/virtio-comment/20230511163020.708427-1-parav@nvidia.com/T/#u

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3776
