### ISSUE TITLE
improve PCIx msix register description

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#169]
Problem:
Current wording queue_msix_vector and config_msix_vector says "for MSI-X", which is bit confusing.

Solution:
config_msix_vector and queue_msix_vector are the msix vector number for configuration change and queue related interrupts.

Patch for vote: https://lists.oasis-open.org/archives/virtio-comment/202304/msg00436.html

Patch link for maintainers automation: https://lore.kernel.org/virtio-comment/20230421145434.83774-1-parav@nvidia.com/
(contains reviewed-by, ack by signatures).

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3773
