### ISSUE TITLE
The size of virtio_net_hdr struct are wrong when VIRTIO_NET_HASH_REPORT feature is negotiated.

### ISSUE THREAD

**Issue by CyrilGermond** [oasis-tcs/virtio-spec#170]
Problem statement :
Hard-coded references to the size of virtio_net_hdr struct are wrong when VIRTIO_NET_HASH_REPORT feature is negotiated.

Proposed patch:
https://lists.oasis-open.org/archives/virtio-comment/202211/msg00014.html

**Comment by paravmellanox** [comment]
Following commit fixes the issue:
0080681 virtio-net: Fix receive buffer size calculation text
