### ISSUE TITLE
virtio-net: support inner header hash

### ISSUE THREAD

**Issue by Heng-Qi** [oasis-tcs/virtio-spec#173]
1. Currently, a received encapsulated packet has an outer and an inner header, but
    the virtio device is unable to calculate the hash for the inner header. The same
    flow can traverse through different tunnels, resulting in the encapsulated
    packets being spread across multiple receive queues (refer to the figure below).
    However, in certain scenarios, we may need to direct these encapsulated packets of
    the same flow to a single receive queue. This facilitates the processing
    of the flow by the same CPU to improve performance (warm caches, less locking, etc.).

                   client1                    client2
                      |        +-------+         |
                      +------->|tunnels|<--------+
                               +-------+
                                  |  |
                                  v  v
                          +-----------------+
                          | monitoring host |
                          +-----------------+

    To achieve this, the device can calculate a symmetric hash based on the inner headers
    of the same flow.

    2. For legacy systems, they may lack entropy fields which modern protocols have in
    the outer header, resulting in multiple flows with the same outer header but
    different inner headers being directed to the same receive queue. This results in
    poor receive performance.

    To address this limitation, inner header hash can be used to enable the device to advertise
    the capability to calculate the hash for the inner packet, regaining better receive performance.

Latest v21 patch: https://lists.oasis-open.org/archives/virtio-dev/202307/msg00006.html

**Comment by Heng-Qi** [comment]
Hi chairs, I have updated the issue description with the latest patch link:
https://lists.oasis-open.org/archives/virtio-dev/202307/msg00001.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3781
