### ISSUE TITLE
Reserve Device ID 46 for TEE Device

### ISSUE THREAD

**Issue by jeshwanthamd** [oasis-tcs/virtio-spec#175]
Please reserve device ID 46 for the TEE device as requested in https://lists.oasis-open.org/archives/virtio-comment/202309/msg00341.html

**Comment by jeshwanthamd** [comment]
@cohuck Any feedback on this issue?

**Comment by KANGKANGABC** [comment]
You mentioned that there is a certain demand for virtio-tee in the industry, but there are a few things to consider:
1.Whether security can be accepted and whether there are encryption measures to maintain a certain degree of isolation with HostOS?
2.Abstract to what level? API compatible or App compatible or Module compatible?

**Comment by jeshwanthamd** [comment]
> You mentioned that there is a certain demand for virtio-tee in the industry, but there are a few things to consider: 1.Whether security can be accepted and whether there are encryption measures to maintain a certain degree of isolation with HostOS? 2.Abstract to what level? API compatible or App compatible or Module compatible?

Hi @KANGKANGABC 
We are yet to publish the spec, the questions are not in scope at this stage. I would recommend let this issue scope only for reserving an ID for TEE Device.

**Comment by jeshwanthamd** [comment]
Hi,
Below is the updated patch.

https://lists.oasis-open.org/archives/virtio-dev/202309/msg00351.html

**Comment by jeshwanthamd** [comment]
Sent this patch to virtio-comment also as per the review comment.
https://lists.oasis-open.org/archives/virtio-comment/202309/msg00311.html

**Comment by jeshwanthamd** [comment]
@paravmellanox Can you please help take this forward?

**Comment by jeshwanthamd** [comment]
v3 of the patch available in https://lists.oasis-open.org/archives/virtio-comment/202309/msg00341.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3798

**Comment by paravmellanox** [comment]
Following commit fixes the issue:
3fdaa17 virtio-tee: Reserve device ID 46 for TEE device
