### ISSUE TITLE
Support device state handling for PCI VFs

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#176]
Problem statement:

In some systems, there is a need to capture the state of all or part of
a device and subsequently restore either the same device or a
different one to this captured state.
This can be useful for debug, snapshot, migration etc use cases.

Solution:
A set of administration commands using existing infrastructure can facilitate query and setting the device state and stop the device before setting such state.

Link to the proposed spec:
https://lore.kernel.org/virtio-comment/20240601145042.2074739-2-parav@nvidia.com/T/#u

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://groups.oasis-open.org/higherlogic/ws/public/ballot?id=3842
