### ISSUE TITLE
virtio-net: Support packet match fields based receive packet steering/forwarding

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#179]
Problem statement:
  Currently packet allow/drop interface has few limitations.
  
  1. Driver cannot add or delete an individual entry for mac and vlan.
  2. Driver cannot select mac+vlan combination for which
      to allow/drop packet.
  3. Driver cannot not set other commonly used packet match fields
      such as IP header fields, TCP, UDP, SCP header fields.
  4. Driver cannot steer specific packets based on the match
     fields to specific receiveq.
  5. Driver do not have multiple or dedicated virtqueues to
      perform flow filter requests in accelerated manner in
      the device.
  
  Solution:
  Flow filter as generic framework overcome above limitations.
  
  As starting point it is useful to support at least two use cases.
  a. ARFS
  b. ethtool ntuple steering

Patch link: https://lore.kernel.org/virtio-comment/20240604132903.2093195-1-parav@nvidia.com/T/#t

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://groups.oasis-open.org/higherlogic/ws/public/ballot?id=3839

**Comment by paravmellanox** [comment]
Following commits fix the issue:
3b7b737 virtio-net: Add flow filter device and driver requirements
224e98b virtio-net: Add flow filter group, classifier and rule resource objects
899bb0c virtio-net: Add flow filter capability
7b3bdd6 virtio-net: Add theory of operation for flow filter
5040f36 admin: Add device resource objects admin commands
738f0a2 admin: Add theory of operation for device resource objects
d60a390 admin: Add capability admin commands
72a91e6 admin: Prepare table for multipage listing
88a24d2 admin: Add theory of operation for capability admin commands
bfe175d admin: Use already defined names for the legacy commands
fdd39cf admin: Introduce self group
