### ISSUE TITLE
virtio-net: Clarify the size of virtio_net_hdr for tx, rx along with receive buffer size

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#183]
There are few small issues around size of receive buffer and size of the
struct virtio_net_hdr as following.

1. VIRTIO_NET_F_HASH_REPORT is only applicable on the rx side packet processing.
   However it changes the size of the struct virtio_net_hdr for the tx side
   as well. This was not clarified when VIRTIO_NET_F_HASH_REPORT feature was
   introduced.

2. Receive buffer size calculation description and requirements did not
   reflect negotiation of VIRTIO_NET_F_HASH_REPORT.

3. Receive buffer size calculation was incorrect for ipv6 guest gso feature.

Above issue 2 was reported in [1].
Since issue 2 and 3 both touches the same set of requirements and description,
they are updated under a new issue along with tx side fix as well touching the
clarification needed for VIRTIO_NET_F_HASH_REPORT.

Hence above three issues are fixed under issue of [2].
[1] https://github.com/oasis-tcs/virtio-spec/issues/170
[2] https://github.com/oasis-tcs/virtio-spec/issues/183

Fix: https://lore.kernel.org/virtio-comment/20240606102014.2103986-1-parav@nvidia.com/T/#u

**Comment by mstsirkin** [comment]
reviewer pointed out that we capitalize MUST. pls fix, post, update link here and we'll vote

**Comment by paravmellanox** [comment]
fix, reposted, link updated.

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://groups.oasis-open.org/higherlogic/ws/public/ballot?id=3833

**Comment by paravmellanox** [comment]
Following commits fixe this issue:
bf0fdf8 virtio-net: Clarify the size of the struct virtio_net_hdr for tx
0080681 virtio-net: Fix receive buffer size calculation text

**Comment by paravmellanox** [comment]
Following commits fixe this issue:
https://github.com/oasis-tcs/virtio-spec/commit/bf0fdf8ba828b694a22c44d45cb3fd34cf813e99 virtio-net: Clarify the size of the struct virtio_net_hdr for tx
https://github.com/oasis-tcs/virtio-spec/commit/00806815385340dd411cc67df3f6837935bb5e26 virtio-net: Fix receive buffer size calculation text
