### ISSUE TITLE
virtio-snd: add more supported sampling rates

### ISSUE THREAD

**Issue by aditpape** [oasis-tcs/virtio-spec#184]
Problem:
virtio soundcard does not support sampling rate of 24kHz used for e.g. 'HD voice' or 'super wide band voice call'

Analysis:
virtio claims to be inspired from Intel HDA spec - according to that spec the range of possible sampling rates is derived from the two base rates **44100** and **48000** by applying **multiplier 1..4** and/or **divisor 1..8**

--> 24kHz is matching 48kHz divided by 2 and falls into such standardized range.

Discussion:
https://lists.oasis-open.org/archives/virtio-comment/202401/msg00134.html

Patch:
https://lists.oasis-open.org/archives/virtio-comment/202402/msg00010.html

**Comment by aditpape** [comment]
Dear TC,
is there enough information given to initiate a voting or is there anything missing from my end?
THX, Regards,
Andreas

**Comment by paravmellanox** [comment]
Following commit fixes the issue:
37c6a40 sound: add sampling rates 12000Hz and 24000Hz
