### ISSUE TITLE
Add virtio CAN device specification

### ISSUE THREAD

**Issue by golubevmikhail** [oasis-tcs/virtio-spec#186]
Add base specification for virtio-can (device 36).
https://lore.kernel.org/virtio-comment/20230609142243.199074-1-Mikhail.Golubev-Ciuchea@opensynergy.com/

RFC v2: https://lore.kernel.org/virtio-comment/20220825133410.18367-1-harald.mommer@opensynergy.com/
RFC: https://lore.kernel.org/virtio-comment/20210401152013.17980-1-harald.mommer@opensynergy.com/

Proposed patch: https://lists.oasis-open.org/archives/virtio-comment/202306/msg00228.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3814

**Comment by paravmellanox** [comment]
Following commit fixes the issue:
07bb9f7 virtio-can: Device specification.
