### ISSUE TITLE
Reserve device ID 47 for CPU balloon device

### ISSUE THREAD

**Issue by shujunxue** [oasis-tcs/virtio-spec#187]
Please reserve device ID 47 for the CPU balloon device as requested in https://lists.oasis-open.org/archives/virtio-dev/202401/msg00061.html, thank you.

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3813

**Comment by paravmellanox** [comment]
Following commit fixes the issue:
878a5e7 Define the DEVICE ID of Virtio Cpu balloon device as 47.
