### ISSUE TITLE
Add virtio SPI device specification

### ISSUE THREAD

**Issue by HaixuCui** [oasis-tcs/virtio-spec#189]
Add base specification for virtio-spi (device 45).

Patches:
https://lists.oasis-open.org/archives/virtio-comment/202401/msg00006.html
https://lists.oasis-open.org/archives/virtio-comment/202401/msg00007.html
https://lists.oasis-open.org/archives/virtio-comment/202401/msg00008.html

**Comment by paravmellanox** [comment]
Following commit fixes the issue:
a402acc virtio-spi: add the device specification
