### ISSUE TITLE
add virtio crypto device specification

### ISSUE THREAD

**Issue by gongleiarei** [oasis-tcs/virtio-spec#19]
Add virtio crypto device documentation to virtio spec.

http://patchwork.ozlabs.org/cover/961653/
http://patchwork.ozlabs.org/patch/961654/
http://patchwork.ozlabs.org/patch/961652/

https://lists.oasis-open.org/archives/virtio-dev/201808/msg00031.html
https://lists.oasis-open.org/archives/virtio-dev/201808/msg00030.html
https://lists.oasis-open.org/archives/virtio-dev/201808/msg00029.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3242
