### ISSUE TITLE
virtio-blk: Fix incorrect data type of field num_queues

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#195]
Problem: num_queues was written as u16. It should be le16.

Fix: https://lore.kernel.org/virtio-comment/hqicqs6p5h4r4xcdhmathfiegvcaly76ityqe67erj7c4b65ck@d2n6v53is5ya/T/#m6fc5341ecf3a68b5fc63ed5cd1b231aa2fb99961

**Comment by mstsirkin** [comment]
the link seems to point to review comments not the proposal. Fix it pls and we can vote.

**Comment by paravmellanox** [comment]
Fixed the link.

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://groups.oasis-open.org/higherlogic/ws/public/ballot?id=3832

**Comment by paravmellanox** [comment]
Following commit fixes the issue:
18e47c0 virtio-blk: Fix data type of num_queues field
