### ISSUE TITLE
`virtio_pci_cap64`: specify `offset_hi`, `length_hi` endianness

### ISSUE THREAD

**Issue by mkroening** [oasis-tcs/virtio-spec#196]
We should be explicit about the endianness of `offset_hi` and `length_hi` in `virtio_pci_cap64`.

Proposal: https://lore.kernel.org/virtio-comment/PH0PR12MB5481A6C266BD5303B98AF5EEDCC72@PH0PR12MB5481.namprd12.prod.outlook.com/T/#m6d45232211d1e1b617171189515a5e11c9b7642c

**Comment by mstsirkin** [comment]
consistent with 32 bit cap

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://groups.oasis-open.org/higherlogic/ws/public/ballot?id=3841

**Comment by paravmellanox** [comment]
Following commit fixes this issue:
9b3129f virtio_pci_cap64: specify offset_hi, length_hi endianness
