### ISSUE TITLE
virtio network device: support for RSC compatibility with WHCK requirements

### ISSUE THREAD

**Issue by ybendito** [oasis-tcs/virtio-spec#20]
Currently virtio network device supports reassembly of received TCP segments, controlled by feature bits VIRTIO_NET_F_GUEST_TSO4 and VIRTIO_NET_F_GUEST_TSO6. This feature has a gap with Windows hardware compatibility requirements. In addition to packet reassembly it is required to coalesce duplicate ack packets and report number of coalesced segments and number of duplicate acks in the metadata of reported packet.
Suggested extension of network device specification includes additional feature bit (extended RSC support) and additional flag bit in virtio network packet header (extended RSC info) which allows to deliver required information in existing header's fields 'csum_start' and 'csum_offset'

http://lists.oasis-open.org/archives/virtio-comment/201810/msg00009.html

**Comment by mstsirkin** [comment]
Please post the proposed wording to the mailing list. If no one objects, as for voting to start.

**Comment by ybendito** [comment]
http://lists.oasis-open.org/archives/virtio-comment/201810/msg00009.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3269

**Comment by mstsirkin** [comment]
Note: need to include this trivial fixup: https://lists.oasis-open.org/archives/virtio-comment/201812/msg00000.html
