### ISSUE TITLE
virtio-transport: Add a section to define mandatory transport requirements

### ISSUE THREAD

**Issue by vireshk** [oasis-tcs/virtio-spec#201]
The current Virtio documentation lacks a set of generic requirements
applicable to all transports. Defining these generic requirements could
be beneficial when integrating support for a new transport.

This outlines the essential requirements that any transport method
must adhere to.

Fix: https://lore.kernel.org/virtio-comment/4c24ede14e2545b2e9c69e7d9b79dc15744fd965.1723647318.git.viresh.kumar@linaro.org/

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://groups.oasis-open.org/higherlogic/ws/public/ballot?id=3846

**Comment by paravmellanox** [comment]
Following commit fixes the issue:
2a5a957 virtio-transport: Add a section to define mandatory transport requirements
