### ISSUE TITLE
content: Reserve device ID 49 for Virtio Media

### ISSUE THREAD

**Issue by aesteve-rh** [oasis-tcs/virtio-spec#202]
Virtio Media can handle video encoders, decoder, and capture devices to be exposed to the guest.
The device can almost transparently handle v4l2-compatible devices in the host.

Here is the [patch](https://lore.kernel.org/virtio-comment/20240906070833.1949727-1-aesteve@redhat.com/T/#u) with the request. Device ID 48 has been reserved for Virtio USB (#193).

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://groups.oasis-open.org/higherlogic/ws/public/ballot?id=3850

**Comment by paravmellanox** [comment]
Following commit fixes the issue:

e98070a content: Reserve ID for media device

The first free device id of 48 is used instead of proposed 49.
