### ISSUE TITLE
virtio: editorial and other small fixes

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#205]
Problem:
1. struct virtio_admin_cmd_dev_parts_metadata_result has hdr_list structure, which missed struct key word annotation.
2. VIRTIO_ADMIN_CMD_DEV_PARTS_METADATA_TYPE_HDR was actually VIRTIO_ADMIN_CMD_DEV_PARTS_METADATA_TYPE_LIST.
3. many spelling errors in drivers, admin and common area to fix.

Fix:
https://lore.kernel.org/virtio-comment/20240916030835.68178-1-parav@nvidia.com/T/#t

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://groups.oasis-open.org/higherlogic/ws/public/ballot?id=3849

**Comment by paravmellanox** [comment]
Following commits fix the issue:
9d60d84 common: editorial: Fix spelling errors
ec1845b gpu: editorial: Fix spelling errors
b820c61 crypto: editorial: Fix spelling errors
9081da1 device-parts: editorial: Fix metadata type name
1d38844 device-parts: editorial: Add missing struct keyword
