### ISSUE TITLE
virtio-net: Define control vq related device parts

### ISSUE THREAD

**Issue by paravmellanox** [oasis-tcs/virtio-spec#209]
Problem statement:

Currently device configuration done using control virtqueue commands by the virtio net driver is not captured in any device parts.

solution:
define these device parts by utilizing existing device parts, control virtqueue commands structure, fields and values.

spec patch: https://lore.kernel.org/virtio-comment/20241020114141.451478-1-parav@nvidia.com/T/#t

**Comment by MatiasVara** [comment]
nada

**Comment by MatiasVara** [comment]
BALLOT CREATED AT URL: https://groups.oasis-open.org/higherlogic/ws/public/ballot?id=3858

**Comment by paravmellanox** [comment]
merged with commits 
b2990c8 virtio-net: Define cvq configuration related device parts
f21f831 device-parts: Add device type specific raw selector
c8c01f2 device-parts: editorial: Replace duplicated part type
