### ISSUE TITLE
Various typos, grammar and cosmetic fixes

### ISSUE THREAD

**Issue by DanielMarcovitch** [oasis-tcs/virtio-spec#24]
(1) Under: 2.6.12 Supplying Buffers to The Device
      text: The driver performs **suitable a** memory barrier
      fix: The driver performs **a suitable** memory barrier

(2) Under: 2.6.5.2 Driver Requirements: The Virtqueue Descriptor Table
    text: Drivers MUST NOT add a descriptor chain **over than** 2^32 bytes **long** in total
    fix : Drivers MUST NOT add a descriptor chain **longer than** 2^32 bytes in total

(3) under 2.7.5 Scatter-Gather Support
     text: mixing **direct and direct** descriptors in a ring is valid,
     fix: mixing **indirect and non-indirect** descriptors in a ring is valid

(4) under: 3.1.1 Driver Requirements: Device Initialization
     text: Set the ACKNOWLEDGE status bit: the guest OS has **notice** the device
     fix: Set the ACKNOWLEDGE status bit: the guest OS has **noticed** the device

(5) under 4.1.4.3 Common configuration structure layout
     text: On reset, specifies the maximum queue size supported by **the hypervisor**. This
can be modified by **driver** to reduce memory requirements.
     fix: On reset, specifies the maximum queue size supported by **the device**. This
can be modified by **the driver** to reduce memory requirements.

Fix proposed in patchset:
https://www.mail-archive.com/virtio-dev@lists.oasis-open.org/msg04008.html

**Comment by DanielMarcovitch** [comment]
the above is the cover note - patches themselves under:

https://www.mail-archive.com/virtio-dev@lists.oasis-open.org/msg04006.html
https://www.mail-archive.com/virtio-dev@lists.oasis-open.org/msg04007.html

**Comment by DanielMarcovitch** [comment]
accidentally closed - reopening

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3271
