### ISSUE TITLE
virtio-blk: discard and write zeroes clarifications

### ISSUE THREAD

**Issue by stefanha** [oasis-tcs/virtio-spec#32]
Review and implementation of the upcoming VIRTIO 1.1 virtio-blk discard and write zeroes command has led to several requests for clarification.  I have submitted patches to take care of them.

The spec changes are available here:
https://lists.oasis-open.org/archives/virtio-dev/201901/msg00134.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3307
