### ISSUE TITLE
virtio-balloon: support VIRTIO_BALLOON_F_FREE_PAGE_HINT and VIRTIO_BALLOON_F_PAGE_POISON

### ISSUE THREAD

**Issue by wei-w-wang** [oasis-tcs/virtio-spec#33]
Add support to virtio-balloon to report guest free memory hint and memory poisoning value to host.
More descriptions: https://lkml.org/lkml/2018/8/27/29

**Comment by mstsirkin** [comment]
Can you post a proposed patch to the spec on the virtio tc mailing list please?

**Comment by wei-w-wang** [comment]
OK, I’ll do.

Best,
Wei

**Comment by cohuck** [comment]
I think this is handled via of https://github.com/oasis-tcs/virtio-spec/issues/84 -- please confirm; we can close this, I think.

**Comment by wei-w-wang** [comment]
Yes, that’s already included in #84, I think it could be closed, thanks!

Best,
Wei

**Comment by wei-w-wang** [comment]
It's already included in #84.
