### ISSUE TITLE
virtio-blk: discard and write zeroes multi-segment clarifications

### ISSUE THREAD

**Issue by stefanha** [oasis-tcs/virtio-spec#34]
The ability to submit multiple segments in a discard or write zeroes request has raised several questions that need clarification.

Patch: https://lists.oasis-open.org/archives/virtio-dev/201902/msg00167.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3309
