### ISSUE TITLE
virtio ring features: inconsistent naming

### ISSUE THREAD

**Issue by mstsirkin** [oasis-tcs/virtio-spec#36]
Reported-by: Don Wallwork <don.wallwork@broadcom.com>

features like VIRTIO_F_EVENT_IDX and
VIRTIO_F_INDIRECT_DESC do not
appear in Linux kernel or QEMU code; VIRTIO_RING_F_EVENT_IDX and
VIRTIO_RING_F_INDIRECT_DESC
are used instead.

Also noticed that there seems to be an inconsistency in the spec in that
VIRTIO_F_EVENT_IDX is
used in some places and VIRTIO_F_RING_EVENT_IDX is used in others

https://lists.oasis-open.org/archives/virtio-comment/201902/msg00032.html

Proposed patch: https://lists.oasis-open.org/archives/virtio-comment/202105/msg00003.html

**Comment by jnider** [comment]
I don't have permission to modify the bug description (as specified in https://github.com/oasis-tcs/virtio-spec#use-of-github-issues) so I'm adding this as a comment for now:
https://lists.oasis-open.org/archives/virtio-comment/202105/msg00003.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3625
