### ISSUE TITLE
content: reserve virtio device ID for virtio pmem device

### ISSUE THREAD

**Issue by pagupta** [oasis-tcs/virtio-spec#38]
We need a device ID for virtio-pmem devices.  Request to reserve (27).

Spec change are available here:
https://lists.oasis-open.org/archives/virtio-dev/201904/msg00027.html

**Comment by pagupta** [comment]
Since device id 25 is already used by audio device. Request to reserve next available one (26).

Updated spec change is available here:
https://lists.oasis-open.org/archives/virtio-dev/201904/msg00015.html

**Comment by pagupta** [comment]
Since device id 26 is already used by virtio-pmem device. Request to reserve next available one (27).

https://lists.oasis-open.org/archives/virtio-dev/201904/msg00017.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3384
