### ISSUE TITLE
document balloon memory statistics

### ISSUE THREAD

**Issue by nyoxi** [oasis-tcs/virtio-spec#4]
Linux kernel provides some balloon memory statistics that were not included in
the specs. Include them to avoid any ID clashes in the future.

The patch has been reviewed on the mailing list:
https://lists.oasis-open.org/archives/virtio-dev/201803/msg00256.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/apps/org/workgroup/virtio/ballot.php?id=3180

**Comment by mstsirkin** [comment]
Original description pointed to
https://lists.oasis-open.org/archives/virtio-dev/201803/msg00154.html
fixing to point to the actual patch that was applied:
https://lists.oasis-open.org/archives/virtio-dev/201803/msg00256.html

**Comment by mstsirkin** [comment]
Resolved-by: commit 58622197571d5160c6cb7f95a112f87ee604f703
