### ISSUE TITLE
Add shared memory regions

### ISSUE THREAD

**Issue by dagrh** [oasis-tcs/virtio-spec#40]
Please merge the 'Large shared memory regions' definitions from:

https://lists.oasis-open.org/archives/virtio-dev/201907/msg00021.html

**Comment by dagrh** [comment]
Now got a full set of Review-by's:
https://lists.oasis-open.org/archives/virtio-dev/201907/msg00027.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3415
