### ISSUE TITLE
Reserve id for virtio-audio device

### ISSUE THREAD

**Issue by bonzini** [oasis-tcs/virtio-spec#42]
Project ACRN has a virtio-audio device. Unfortunately, the id they are using is
already reserved in the virtio specification, but it is nevertheless useful to
have one.

Link: https://lists.oasis-open.org/archives/virtio/201903/msg00074.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3410
