### ISSUE TITLE
virtio network device: define interface for steering control / RSS

### ISSUE THREAD

**Issue by ybendito** [oasis-tcs/virtio-spec#48]
In case of multiple queue pairs the spec currently defines only automatic/uncontrolled steering capability. In order to support RSS (receive side scaling) feature on VM and especially to let bare metal virtio device to use simpler steering mechanism,  respective interface must be defined in the spec

Latest patch
https://lists.oasis-open.org/archives/virtio-comment/201911/msg00014.html
~~https://lists.oasis-open.org/archives/virtio-comment/201910/msg00039.html~~
~~https://lists.oasis-open.org/archives/virtio-comment/201910/msg00020.html~~
~~https://lists.oasis-open.org/archives/virtio-comment/201910/msg00001.html~~

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3448
