### ISSUE TITLE
virtio-fs: add virtio file system device

### ISSUE THREAD

**Issue by stefanha** [oasis-tcs/virtio-spec#49]
I propose voting on the virtio-fs device.  It provides file system access.  Spec discussion has died down and Linux/QEMU patches are making their way upstream.

https://lists.oasis-open.org/archives/virtio-dev/201908/msg00112.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3428
