### ISSUE TITLE
Add DISCARD and WRITE ZEROES commands to virtio-blk specification

### ISSUE THREAD

**Issue by changpe1** [oasis-tcs/virtio-spec#5]
Existing virtio-blk protocol doesn't have DISCARD/WRITE ZEROES support, this will impact the performance when using SSD backend over file systems.

Here is the proposal to extend existing virtio-blk protocol to support DISCARD/WRITE ZEROES commands.

Patch was reviewed at the following link:

https://lists.oasis-open.org/archives/virtio-dev/201803/msg00132.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/apps/org/workgroup/virtio/ballot.php?id=3181

**Comment by mstsirkin** [comment]
Resolved-by: commit 88c8553838346b26be4460485cc57c38850b36f7
