### ISSUE TITLE
Add virtio RPMB device specification

### ISSUE THREAD

**Issue by yang8621** [oasis-tcs/virtio-spec#53]
Add virtio RPMB device documentation to virtio spec.

v1: https://lists.oasis-open.org/archives/virtio-dev/201907/msg00059.html
https://lists.oasis-open.org/archives/virtio-dev/201907/msg00058.html
v2: https://lists.oasis-open.org/archives/virtio-dev/201907/msg00068.html
v3: https://lists.oasis-open.org/archives/virtio-dev/201908/msg00020.html
v4: https://lists.oasis-open.org/archives/virtio-dev/201908/msg00109.html
https://lists.oasis-open.org/archives/virtio-dev/201908/msg00110.html
v5: https://lists.oasis-open.org/archives/virtio-dev/201909/msg00128.html
v6 (latest): https://lists.oasis-open.org/archives/virtio-dev/201910/msg00038.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3439

**Comment by mstsirkin** [comment]
This was approved but is clearly incomplete without an ID reserved.
Will commit once https://github.com/oasis-tcs/virtio-spec/issues/58
is approved.
