### ISSUE TITLE
Entropy device: 5.4.6.1 lists wrong requirement

### ISSUE THREAD

**Issue by ShayDamir** [oasis-tcs/virtio-spec#55]
5.4.6.1 says: 

> The driver MUST NOT place driver-readable buffers into the queue.

It looks like it must be changed to 

> The driver MUST NOT place device-readable buffers into the queue.

OR 

> The driver MUST NOT place driver-writeable buffers into the queue.

Rationale:

The point of Entropy device is that driver supplies a buffer, and device fills it, so the buffer must be
device-writeable and driver-readable. 

Buffers that are device-readable (driver-writeable) cannot be used by device, so they must be forbidden.

Proposal (by mst): https://lists.oasis-open.org/archives/virtio-comment/201911/msg00040.html

**Comment by ShayDamir** [comment]
This is the place of the issue in the current master:
https://github.com/oasis-tcs/virtio-spec/blob/30d8e1ad22f7e1207664723a2815359b4992c927/content.tex#L4615

**Comment by mstsirkin** [comment]
On Mon, Nov 11, 2019 at 04:08:51AM -0800, Damir Shaykhutdinov wrote:
> 5.4.6.1 says:
> 
>     The driver MUST NOT place driver-readable buffers into the queue.
> 
> It looks like it must be changed to
> 
>     The driver MUST NOT place device-readable buffers into the queue.
> 
> OR
> 
>     The driver MUST NOT place driver-writeable buffers into the queue.
> 
> Rationale:
> 
> The point of Entropy device is that driver supplies a buffer, and device fills
> it, so the buffer must be
> device-writeable and driver-readable.
> 
> Buffers that are device-readable (driver-writeable) cannot be used by device,
> so they must be forbidden.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


Please remeber to also report the issue on the virtio comment mailing list.
https://github.com/oasis-tcs/virtio-spec/#use-of-github-issues

Thanks!

**Comment by mstsirkin** [comment]
Damir ping, can you please send an email to the list so we
can resolve this? Thanks!

**Comment by mstsirkin** [comment]
OK I posted a patch to fix this.
Could reporter please supply his name and affiliation for proper attribution in the change log?

**Comment by mstsirkin** [comment]
closed by mistake.

**Comment by ShayDamir** [comment]
Sorry for late answer, I was on vacation.

My full name is Damir Shaikhutdinov, and I'm affiliated with OpenSynergy GmbH

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3466
