### ISSUE TITLE
split-ring: Demand that a device must not change descriptor entries

### ISSUE THREAD

**Issue by jan-kiszka** [oasis-tcs/virtio-spec#56]
So far the spec only indirectly says that a descriptor table entry is
not modified by a device when processing it. Make this explicit by
adding it as normative requirement. Existing drivers already depend on
this.

Patch:
https://lists.oasis-open.org/archives/virtio-dev/201911/msg00040.html

**Comment by mstsirkin** [comment]
is this one ready for vote?

**Comment by jan-kiszka** [comment]
Waiting for Rob to answer my questions what exactly is the use case of keeping this device-writable.

**Comment by mstsirkin** [comment]
vote?defer?close?

**Comment by cohuck** [comment]
Defer? I did not see any further clarification on the possible use cases.

**Comment by mstsirkin** [comment]
How about making it weaker, with SHOULD NOT instead of MUST NOT?

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3480
