### ISSUE TITLE
virtio-net: Add support for correct hdr_len field

### ISSUE THREAD

**Issue by vm831** [oasis-tcs/virtio-spec#57]
Some devices benefit from the knowledge of the exact header length (for instance for TSO processing).
Add a feature bit for a driver that is capable of providing the correct header length, and a device that can benefit from this knowledge.

The patch:
[https://lists.oasis-open.org/archives/virtio-comment/201911/msg00002.html](https://lists.oasis-open.org/archives/virtio-comment/201911/msg00002.html)

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3444

**Comment by cohuck** [comment]
Non-material tweaks on top of this:
https://lists.oasis-open.org/archives/virtio-comment/201911/msg00030.html
