### ISSUE TITLE
virtio-net: Add missing flag define to struct

### ISSUE THREAD

**Issue by sameehj** [oasis-tcs/virtio-spec#6]
The flag VIRTIO_NET_HDR_F_DATA_VALID is aleady mentioned in the virtio-net
spec however it is not defined in the struct. This flag is already defined
and used in virtio-net device in Qemu as well as some of it's drivers.

Patch on the mailing list:
https://lists.oasis-open.org/archives/virtio-dev/201712/msg00143.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/apps/org/workgroup/virtio/ballot.php?id=3182

**Comment by mstsirkin** [comment]
Resolved-by: commit 602987fba144d996d17bab02c32f2fb91d28b8fa
