### ISSUE TITLE
virtio-blk: document VIRTIO_BLK_T_GET_ID

### ISSUE THREAD

**Issue by stefanha** [oasis-tcs/virtio-spec#63]
Add the VIRTIO_BLK_T_GET_ID request type to the virtio-blk specification:

https://lists.oasis-open.org/archives/virtio-dev/201912/msg00000.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3536
