### ISSUE TITLE
virtio-gpu: some edid clarifications

### ISSUE THREAD

**Issue by kraxel** [oasis-tcs/virtio-spec#64]
Clarify how the driver should use the new VIRTIO_GPU_CMD_GET_EDID
command when the VIRTIO_GPU_F_EDID feature is provided by the device.

https://lists.oasis-open.org/archives/virtio-dev/201911/msg00148.html

**Comment by mstsirkin** [comment]
is this ready for a vote?

**Comment by kraxel** [comment]
I think so, yes.  No objections on the list.  xmas holiday period is long over too ;)
(Same goes for #65)

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3472

**Comment by mstsirkin** [comment]
Fixed by:

commit 0c0dd715152cbbdc1d87e8d193d4c56d2b0bb5fe
Author: Gerd Hoffmann <kraxel@redhat.com>
Date:   Thu Nov 28 12:42:43 2019 +0100
    virtio-gpu: some edid clarifications
    
    Add some notes about fetching the EDID information.
    
    Fixes: https://github.com/oasis-tcs/virtio-spec/issues/64
    Signed-off-by: Gerd Hoffmann <kraxel@redhat.com>
    Signed-off-by: Michael S. Tsirkin <mst@redhat.com>
