### ISSUE TITLE
virtio-net: Define possibility to deliver per-packet hash

### ISSUE THREAD

**Issue by ybendito** [oasis-tcs/virtio-spec#66]
Feature VIRTIO_NET_F_HASH_REPORT indicates the device is able to deliver per-packet hash. If negotiated, this extends packet structure to include calculated hash value and hash type, In this case the device also support commands for configuration of enabled hashes and a key for hash calculation.

https://lists.oasis-open.org/archives/virtio-comment/202002/msg00034.html

**Comment by ybendito** [comment]
Latest commit:
https://lists.oasis-open.org/archives/virtio-comment/201912/msg00016.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3478
