### ISSUE TITLE
content: reserve device IDs for video encoder and decoder device

### ISSUE THREAD

**Issue by keiichiw** [oasis-tcs/virtio-spec#67]
The virtio-video protocol is for video encoder and decoder. ([RFCv1], [v2]) 
It needs two device IDs for decoder and encoder respectively.

We requested 30 and 31 in [this patch](https://markmail.org/thread/bzfqdwk47pecnsah), as 29 had been requested for [hwsim wireless simulation](https://markmail.org/message/q6qdl4zoycpkg3w5). 

https://lists.oasis-open.org/archives/virtio-comment/201912/msg00031.html

[RFCv1]: https://markmail.org/thread/gtip3dil4gwr3qan
[v2]: https://markmail.org/thread/4ufu3l3mwyoojxjb

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3468

**Comment by keiichiw** [comment]
Let me close this issue because the patch was merged.
https://github.com/oasis-tcs/virtio-spec/commit/6914d2df75ec0479df59ae9054ee4be1564c5172

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3486

**Comment by keiichiw** [comment]
@mstsirkin Why did you create a new ballot again for this issue? You maybe intended #68 instead of here, didn't you?

**Comment by mstsirkin** [comment]
oh right. closing

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3498

**Comment by keiichiw** [comment]
@mstsirkin Why did you create the ballot again? The patch was already merged.

**Comment by mstsirkin** [comment]
It keeps popping up because the commit lacked a Fixes tag. Sorry.
