### ISSUE TITLE
content: reserve device ID for mac80211_hwsim

### ISSUE THREAD

**Issue by jmberg** [oasis-tcs/virtio-spec#68]
As described in the patch, we'd like to have a device ID for Linux's hwsim to allow multiple VMs to participate in a simulated wireless network.

https://lists.oasis-open.org/archives/virtio-comment/201911/msg00051.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3487
