### ISSUE TITLE
virtio-net: Fix VIRTIO_NET_F_GUEST_HDRLEN feature definition

### ISSUE THREAD

**Issue by vm831** [oasis-tcs/virtio-spec#72]
Fix driver and device requirements with regards to the VIRTIO_NET_F_GUEST_HDRLEN feature - 'hdr_len' must be accurate only for TSO/UFO packets.

The patch:
[https://lists.oasis-open.org/archives/virtio-comment/202002/msg00053.html](https://lists.oasis-open.org/archives/virtio-comment/202002/msg00053.html)

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3481
