### ISSUE TITLE
content: reserve device ID 32 for SCMI device

### ISSUE THREAD

**Issue by peter-hilber-at-opensynergy-dot-com** [oasis-tcs/virtio-spec#74]
virtio-scmi provides a simple transport for the Arm SCMI (*S*ystem *C*ontrol and *M*anagement *I*nterface) protocol. [This patch requests device ID 32](https://lists.oasis-open.org/archives/virtio-comment/202003/msg00012.html), as device ID 31 has been requested for virtio-video (#67).

There is also patch for the device itself ([PATCH v3] [Add virtio SCMI device specification](https://lists.oasis-open.org/archives/virtio-comment/202003/msg00033.html)).

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3492

**Comment by mattimo** [comment]
Can the vote be re-created, there are valid objections to the vote as the URL provided in the ballot is pointing the the patch that adds the protocol instead of the patch that reserves the device ID?

**Comment by mstsirkin** [comment]
On Mon, Apr 06, 2020 at 07:31:34AM -0700, Matti Möll wrote:
> Can the vote be re-created, there are valid objections to the vote as the URL
> provided in the ballot is pointing the the patch that adds the protocol instead
> of the patch that reserves the device ID?


I can cancel the vote, sure.
Pls fix the github issue to have description point to the correct
proposal and request and the request a new vote.

**Comment by peter-hilber-at-opensynergy-dot-com** [comment]
> I can cancel the vote, sure. Pls fix the github issue to have description point to the correct proposal and request and the request a new vote.

FYI: I already updated the issue and requested a new vote: https://lists.oasis-open.org/archives/virtio-comment/202004/msg00001.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3496

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3499
