### ISSUE TITLE
virtio-net: Speed and Duplex documentation mistakes

### ISSUE THREAD

**Issue by Manorhos** [oasis-tcs/virtio-spec#75]
The spec says that the duplex field has the value 0x00 for full duplex and 0x01 for half duplex, however the current implementations in QEMU and the virtio Linux driver use the values the other way around. DUPLEX_FULL is defined as 1 and DUPLEX_HALF is defined as 0. These values are put into the field if the corresponding config value (duplex=full/half) is found.

Also, when describing the possible values of the speed config field, the maximum value and the value for unknown speed are listed as "0x7ffffffff" and "0xfffffffff" respectively. They both have an extraneous "f" nibble, as they wouldn't fit into a 32-bit field this way.

Proposal ("[PATCH] virtio-net: fix speed, duplex") can be found at:
https://lists.oasis-open.org/archives/virtio-comment/202009/msg00000.html

**Comment by mstsirkin** [comment]
Can I ask you to please report this on the mailing list according to virtio TC bylaws?

**Comment by Manorhos** [comment]
Oh, whoops, I thought just a GitHub issue would be enough for small things, sorry.
I just saw you sent a patch to the comment mailing list already, would it be okay if I just added that as the proposal link to my initial post in this issue?

**Comment by mstsirkin** [comment]
On Tue, Sep 01, 2020 at 08:14:38AM -0700, Manorhos wrote:
> Oh, whoops, I thought just a GitHub issue would be enough for small things,
> sorry.
> I just saw you sent a patch to the comment mailing list already, would it be
> okay if I just added that as the proposal link to my initial post in this
> issue?


Yes, but please reply to the email and send your
Signed-off-by: <name> <email>

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3643
