### ISSUE TITLE
add virtio-pmem spec

### ISSUE THREAD

**Issue by malchev** [oasis-tcs/virtio-spec#78]
Spec's implemented in Linux, QEMU, and CrosVM.  However, aside from the device ID having been reserved, the spec itself does not appear to have been officially considered.

Device ID was reserved here:
https://github.com/oasis-tcs/virtio-spec/issues/38

Original spec proposal:
https://lists.oasis-open.org/archives/virtio-dev/201903/msg00083.html
Rebased patch:
https://github.com/oasis-tcs/virtio-spec/pull/77

Proposed spec: https://lists.oasis-open.org/archives/virtio-dev/202110/msg00039.html

**Comment by mstsirkin** [comment]
Please follow the process outlined in
https://github.com/oasis-tcs/virtio-spec#providing-feedback

**Comment by malchev** [comment]
Will do.  It's not clear to me whether I should send this patch to virtio-comment or virtio-dev?  Instructions for emailing virtio-comment describe sending the patch, while instructions for emailing virtio-dev describe referencing this issue.

**Comment by mstsirkin** [comment]
virtio-comment.
virtio-dev is for implementation discussions, e.g. that's where you would copy linux or qemu patches.

**Comment by davidhildenbrand** [comment]
CCing @pagupta

**Comment by cohuck** [comment]
Has there been any follow-up on this?

**Comment by pagupta** [comment]
I will do the followup. 

Thanks,
Pankaj

**Comment by cohuck** [comment]
Friendly ping -- has there been any progress?

**Comment by pagupta** [comment]
Latest spec proposal: 

https://lists.oasis-open.org/archives/virtio-dev/202110/msg00039.html
