### ISSUE TITLE
virtio-net - Receiving Used Buffers From The Device

### ISSUE THREAD

**Issue by atomass** [oasis-tcs/virtio-spec#79]
Currently the documentation says:

> it sends a used buffer notification to the driver
> as detailed in section \ref{sec:Basic
> Facilities of a Virtio Device / Packed Virtqueues / Event
> Suppression Structure Format}.

But the referred section does not contain any useful information on how a device should notify a driver. Is this a mistake?

**Comment by mstsirkin** [comment]
please ask questions on the mailing list. issue tracker is solely to track proposal voting.

**Comment by cohuck** [comment]
Closing this per the comment above. Also, see https://github.com/oasis-tcs/virtio-spec#use-of-github-issues

Feel free to ask questions and/or propose changes via virtio-comment@lists.oasis-open.org
