### ISSUE TITLE
virtio rpmb NVME support

### ISSUE THREAD

**Issue by dlegaultbbry** [oasis-tcs/virtio-spec#80]
The virtio RPMB spec should perhaps be amended to include the NVMe RPMB frame format which is completely different than eMMC/UFS format before virtio 1.2 is released. This may lead to the spec requiring some flags to signal what type of RPMB device the host is providing such that the guests may be able to format frames in the appropriate format for the device.

https://nvmexpress.org/developers/nvme-specification/

See figure 469

The control frame is a single entity of 256 bytes long while optional data (read/write) comes in the 512 byte sectors (eMMC/UFS = 256 bytes). All fields are also Little Endian.

eMMC/UFS use 512 byte frames (with inline data) with Big Endian fields.

**Comment by mstsirkin** [comment]
Note that the TC will not respond to comments provided in github issues: github issues are used solely to track integration of comments into the specification.
https://github.com/oasis-tcs/virtio-spec#use-of-github-issues

**Comment by cohuck** [comment]
As by the comment above, I'll close this issue now.

If a patch implementing this change is posted and reviewed, feel free to reopen and include the link to the patch in the issue description so we can use this to track voting and inclusion.
