### ISSUE TITLE
virtio-mem: add initial device specification

### ISSUE THREAD

**Issue by davidhildenbrand** [oasis-tcs/virtio-spec#82]
Add the initial device specification for virtio-mem. The Linux implementation is in 5.8-rc1, the QEMU version is on its way upstream and should get merged soon.

Latest posted proposal ("[PATCH v2 0/3] virtio-spec: Add virtio-mem device specification") can be found at https://lists.oasis-open.org/archives/virtio-comment/202006/msg00010.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3515
