### ISSUE TITLE
virtio-balloon: Update spec to include features hinting, poison, and reporting

### ISSUE THREAD

**Issue by ahduyck** [oasis-tcs/virtio-spec#84]
Update the device specification for virtio-balloon to include recently added features hinting, poison, and reporting. Both the hinting and poison feature were added some time ago, but not documented. The page reporting Linux implementation is already upstream and was included in the 5.8 [kernel](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b0c504f154718904ae49349147e3b7e6ae91ffdc) and the [QEMU](https://lists.oasis-open.org/archives/virtio-dev/202004/msg00180.html) portion is already upstream.

Latest posted proposal ("[PATCH v8 0/3] virtio-spec: Add documentation for recently added balloon features") can be found at: https://lists.oasis-open.org/archives/virtio-comment/202008/msg00054.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3521

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3522

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3523
