### ISSUE TITLE
content: Reserve device ID 34 for I2C adapter

### ISSUE THREAD

**Issue by ssqre** [oasis-tcs/virtio-spec#85]
Request the ID 34 for I2C adapter. The upstream code patch is under review ([v1](https://www.spinics.net/lists/linux-i2c/msg47661.html), [v2](https://www.spinics.net/lists/linux-i2c/msg48032.html), [v3](https://lists.linuxfoundation.org/pipermail/virtualization/2020-September/049929.html)) . 

The ID request: https://lists.oasis-open.org/archives/virtio-comment/202009/msg00009.html

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3530
