### ISSUE TITLE
virtio-gpu resource blob and host visible features

### ISSUE THREAD

**Issue by gurchetansingh** [oasis-tcs/virtio-spec#86]
These patches define:
      (1) blob resources for use with virtio_gpu
      (2) a zero-copy mechanism for using host buffers with virtio_gpu

The latest patches are available at:
https://lists.oasis-open.org/archives/virtio-comment/202009/msg00003.html
https://lists.oasis-open.org/archives/virtio-comment/202009/msg00004.html
https://lists.oasis-open.org/archives/virtio-comment/202009/msg00005.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3535
