### ISSUE TITLE
Add virtio-i2c device specification

### ISSUE THREAD

**Issue by ssqre** [oasis-tcs/virtio-spec#88]
The specification: ([v1](https://lists.oasis-open.org/archives/virtio-comment/202009/msg00021.html), [v2](https://lists.oasis-open.org/archives/virtio-comment/202010/msg00005.html), [v3](https://lists.oasis-open.org/archives/virtio-comment/202010/msg00011.html), [v4](https://lists.oasis-open.org/archives/virtio-comment/202011/msg00005.html), [v5](https://lists.oasis-open.org/archives/virtio-comment/202011/msg00042.html), [v6](https://lists.oasis-open.org/archives/virtio-comment/202012/msg00050.html), [v7](https://lists.oasis-open.org/archives/virtio-comment/202101/msg00008.html)). 

The upstream code patch is under review ([v1](https://www.spinics.net/lists/linux-i2c/msg47661.html), [v2](https://www.spinics.net/lists/linux-i2c/msg48032.html), [v3](https://lists.linuxfoundation.org/pipermail/virtualization/2020-September/049929.html), [v4](https://www.spinics.net/lists/linux-i2c/msg48703.html)) .

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3548

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3553
