### ISSUE TITLE
virtio-net: Add support for the flexible driver notification structure

### ISSUE THREAD

**Issue by vm831** [oasis-tcs/virtio-spec#89]
When the driver is required to send an available buffer notification to the device, it sends the virtqueue number to be notified.
With this new feature, the device can optionally provide a per-virtqueue value for the driver to use in driver notifications, instead of the virtqueue number.
Some devices may benefit from this flexibility by providing, for example, an internal virtqueue identifier, or an internal offset related to the virtqueue number.

The patch:
[https://lists.oasis-open.org/archives/virtio-comment/202011/msg00004.html](https://lists.oasis-open.org/archives/virtio-comment/202011/msg00004.html)

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3539
