### ISSUE TITLE
content: reserve virtio device ID for memory devices

### ISSUE THREAD

**Issue by davidhildenbrand** [oasis-tcs/virtio-spec#9]
We need a device ID for virtio-mem devices. Let's use the next free one (24).

See: [https://lists.oasis-open.org/archives/virtio-dev/201804/msg00291.html](https://lists.oasis-open.org/archives/virtio-dev/201804/msg00291.html)

**Comment by mstsirkin** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3217
