### ISSUE TITLE
typo: VIRTIO_NET_F_MAC_ADDR -> VIRTIO_NET_F_MAC

### ISSUE THREAD

**Issue by mstsirkin** [oasis-tcs/virtio-spec#90]
spec mentions VIRTIO_NET_F_MAC_ADDR which isn't defined.
It seems clear from context that what is meant is VIRTIO_NET_F_MAC which controls whether mac in config space is valid.

https://lists.oasis-open.org/archives/virtio-comment/202012/msg00001.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3545
