### ISSUE TITLE
virtio-mem: minor clarification regarding read-access to unplugged blocks

### ISSUE THREAD

**Issue by davidhildenbrand** [oasis-tcs/virtio-spec#91]
Let's clarify that we don't expect all DMA to work with unplugged blocks.
We really only give guarantees when reading from unplugged memory blocks
via the CPU, e.g., as done by Linux when creating a system dump via
kdump: the new kernel will copy the content of the old (crashed) kernel
via the CPU to user space, from where it will find its final destination
inside the dump file. Note that dumping via makedumpfile under Linux will
avoid reading unplugged blocks completely.

This is a preparation for device passthrough to VMs, whereby such
dedicated devices might not be able to read from unplugged memory blocks.

Proposed patch: [v1](https://lists.oasis-open.org/archives/virtio-comment/202011/msg00023.html)

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3546
