### ISSUE TITLE
Add lifetime metrics to virtio-blk

### ISSUE THREAD

**Issue by egranata** [oasis-tcs/virtio-spec#97]
The specification: [v1](https://lists.oasis-open.org/archives/virtio-dev/202102/msg00034.html) [v2](https://lists.oasis-open.org/archives/virtio-dev/202102/msg00080.html) [v3](https://lists.oasis-open.org/archives/virtio-dev/202103/msg00012.html) [v4](https://lists.oasis-open.org/archives/virtio-dev/202103/msg00038.html) [v5](https://lists.oasis-open.org/archives/virtio-dev/202103/msg00043.html)

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3589

**Comment by cohuck** [comment]
Closing manually, as github does not seem to have picked up the Fixes: tag in 5e9a37b9a5593a6787bb25c0534110dfb63cd0c4
